/*
 *          Copyright Schwenk, Kurt <Kurt.Schwenk@gmx.de> 2020
 * Distributed under the Boost Software License, Version 1.0.
 *    (See accompanying file LICENSE_1_0.txt or copy at
 *          http://www.boost.org/LICENSE_1_0.txt)
 */

#pragma once

#include <array>

namespace dataflow::blocks::outputPredicates {

/**
 * @brief Default output predicate for blocks.
 *
 * @details 
 *  - Default output predicate for blocks.
 *  - Outputs to all channels.
 *  - Does not analyzing the blockOperatorOutput.
 *
 *  @param
 *   blockOperatorOuput... Output generated by the block operator for each channel (not used).
 *
 *
 */
struct OutputAll {
    template <typename... T>
    constexpr std::array<bool, sizeof...(T)> operator()([[maybe_unused]] const T&... blockOperatorOutput) const;
};

} //namespace dataflow::blocks::outputPredicates

#include "../impl/OutputPredicates.hpp"
